### ISSUE TITLE
FB4 Sockeye Predator Energy Density

### ISSUE THREAD

**Issue by AthenaOgden** [jim-breck/FB4#25]
Hi Jim,

I may have found a bug in using Sockeye in FB4. I have attached what the Predator Energy Density tab looks like when I try to run a Sockeye model (Fit to Final Weight) and I use this as my Pred_E.csv input:

day    predator
1        5233
156    5233

![problematic pred energy density](https://user-images.githubusercontent.com/16866905/34798577-7ec85414-f611-11e7-8f35-9c93aae9988f.png)

In case you can't open that attachment, the x-axis is showing weight. But that's not what your Yellow Perch example shows on the x-axis.

When I try to rerun it, sometimes it opens the browser. Maybe I'm doing something wrong, but it seems strange that the plot axes units would change even if I entered some incorrect values.

Athena Ogden
athena.ogden@dfo-mpo.gc.ca
muchado22@gmail.com

**Comment by AthenaOgden** [comment]
I mean that sometimes when I click on the "Predictor Energy Density" tab, the browser opens and no plot appears.

**Comment by davelerouge** [comment]
Athena, the change in axes is due to the predator energy density model you are using. The sockeye salmon is set to use predator energy density model 2, which means that the weight of the fish will determine its energy density regardless of the predator energy density input file. The plot is showing that relationship. If you want to use your own values as for the yellow perch model, you will need to change the predator energy density model (PREDEDEQ) value to 1 under the Sockeye salmon row in the Parameters_official.csv file. I hope this helps.


Cheers,


David

________________________________

**Comment by AthenaOgden** [comment]
Thanks, David. I suppose the browser gets called because of some error I was making.
